# Generated by Django 2.0.6 on 2018-06-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.IntegerField()),
                ('camp_url', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('advertiser', models.CharField(max_length=200)),
                ('camp_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UrlGenerate.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='MobileCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnc', models.IntegerField()),
                ('mcc', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('mnc', models.IntegerField()),
                ('mcc', models.IntegerField()),
                ('android_version', models.CharField(max_length=50)),
                ('phone_make', models.CharField(max_length=100)),
                ('phone_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UrlGenerate.User_Camp'),
        ),
    ]
