# Generated by Django 2.0.6 on 2018-06-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_camp',
            old_name='user_id',
            new_name='uuid',
        ),
    ]
