# Generated by Django 2.0.6 on 2018-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0002_auto_20180618_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='camp_id',
        ),
        migrations.AlterField(
            model_name='user_camp',
            name='uuid',
            field=models.IntegerField(unique=True),
        ),
    ]
