# Generated by Django 2.0.6 on 2018-06-18 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0003_auto_20180618_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='camp_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 11, 30, 46, 883901)),
        ),
        migrations.AlterField(
            model_name='hit',
            name='sms',
            field=models.CharField(default='null', max_length=2000),
        ),
    ]
