# Generated by Django 2.0.6 on 2018-06-18 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0004_auto_20180618_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 11, 31, 37, 434041)),
        ),
    ]
