# Generated by Django 2.0.6 on 2018-06-18 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0005_auto_20180618_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 15, 32, 16, 434797)),
        ),
    ]
