# Generated by Django 2.0.4 on 2018-06-21 05:32

import UrlGenerate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0010_auto_20180618_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('game_pic', models.ImageField(blank=True, null=True, upload_to=UrlGenerate.models.game_directory_path)),
                ('game_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='hit',
            name='sms',
            field=models.CharField(default='XXX', max_length=2000),
        ),
    ]
