# Generated by Django 2.0.4 on 2018-06-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0011_auto_20180621_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_pic',
        ),
    ]
