# Generated by Django 2.0.4 on 2018-06-21 05:42

import UrlGenerate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0012_remove_game_game_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_pic',
            field=models.ImageField(blank=True, null=True, upload_to=UrlGenerate.models.game_directory_path),
        ),
    ]
