# Generated by Django 2.0.4 on 2018-06-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0013_game_game_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_pic',
        ),
    ]
