# Generated by Django 2.0.4 on 2018-06-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0015_game_game_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_url',
            new_name='url',
        ),
    ]
