# Generated by Django 2.0.4 on 2018-06-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlGenerate', '0016_auto_20180621_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pic',
            field=models.URLField(),
        ),
    ]
